##### BEGIN modeco/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS base
##### END modeco/Dockerfile/image-header #####

##### BEGIN modeco/Dockerfile/conteco #####
COPY ./modeco/ /modeco/
RUN rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END modeco/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
##### END image/Dockerfile/build-instructions #####

##### BEGIN modeco/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="modeco" \
    CONTECO_TYPE="traefik" \
    CONTECO_NAME="g1" \
    CONTECO_TAG="v2.0.0" \
    CONTECO_BASE="image.wrapper" \
    CONTECO_BUILD="modeco"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="modeco" \
      io.vcweb.type="traefik" \
      io.vcweb.name="g1" \
      io.vcweb.tag="v2.0.0" \
      io.vcweb.base="image.wrapper" \
      io.vcweb.build="modeco" \
      io.vcweb.label="traefik.g1 - Modeco" \
      io.vcweb.description="The Traefik generation 1 module, providing autodiscovery for the services exposed by the modules." \
      io.vcweb.docker.cmd.help="docker run vcwebio/modeco.traefik.g1 --help"
##### END modeco/Dockerfile/env-labels-footer #####
