#!/usr/bin/env bash

export CONTECO_LABEL="traefik.g1 - Modeco"
export CONTECO_DESCRIPTION="The Traefik generation 1 module, providing autodiscovery for the services exposed by the modules."

export CONTECO_TYPE="traefik"
export CONTECO_NAME="g1"
export CONTECO_TAG="v2.0.4"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
