#!/usr/bin/env bash


prefix="module_traefik_g1_$2"

if [[ "module_traefik_g1_metrics_monitor_heartbeat_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create module_traefik_g1_metrics_monitor_heartbeat_data_volume
	fi
	
if [[ "module_traefik_g1_metrics_monitor_heartbeat_monitors_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create module_traefik_g1_metrics_monitor_heartbeat_monitors_volume
	fi
	
if [[ "module_traefik_g1_metrics_monitor_heartbeat_monitors_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v module_traefik_g1_metrics_monitor_heartbeat_monitors_volume:/usr/share/heartbeat/monitors.d ${CONTECO_REGISTRY}$1 --interactive cp -r /modeco/volumes/metrics_monitor_heartbeat_monitors_volume/* /usr/share/heartbeat/monitors.d
		fi
		
